Mosquito-Alert/Mosquito-Alert-Mobile-App

lib/api/api.dart, lib/pages/forms_pages/adult_report_page.dart, lib/pages/forms_pages/biting_report_page.dart, lib/pages/my_reports_pages/my_reports_page.dart, lib/utils/Utils.dart
```bash
find . -name '*.dart' -exec sed -i 's/DateTime.now()/DateTime.now().toUtc()/g' {} \;
```
=> Bug fixed: added UTC Timezone to all datetimes. Fix #12

lib/api/api.dart
=> Change dev API endpoint to new server

lib/main.dart, lib/pages/forms_pages/components/biting_location_form.dart, lib/utils/Utils.dart
Fixes #60 
- When user never gave permission for location, use 0,0 by default
- When user gave access previously, still show 
|   |   |
| When I gave access before | When I denied the permission |
| <img src="https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/67161f77-0411-4d33-9dc2-452546f907c6" width="200" height="400" /> | <img src="https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/1ab040d3-03e8-4eee-a5fc-4e420cc482c7" width="200" height="400" /> |
=> When location permission is denied, set default location to 0 0

lib/pages/notification_pages/notifications_page.dart
fixes #57 
| Before  | After |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/c5c9564d-19b5-4d89-b8dc-82872535574e)  | ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/f6bdf4ad-24d1-4dfb-87e7-cc258f00d3e9) |
=> Change hour format to 0-23

lib/api/api.dart, lib/models/notification.dart, lib/pages/forms_pages/adult_report_page.dart, lib/pages/forms_pages/biting_report_page.dart, lib/pages/forms_pages/breeding_report_page.dart, lib/pages/forms_pages/components/add_photo_button_widget.dart, lib/pages/forms_pages/components/biting_form.dart, lib/pages/forms_pages/components/biting_location_form.dart, lib/pages/forms_pages/components/could_see_form.dart, lib/pages/forms_pages/components/image_button_widget.dart, lib/pages/forms_pages/components/image_question_option_widget.dart, lib/pages/forms_pages/components/mosquito_parts_form.dart, lib/pages/forms_pages/components/mosquito_type_form.dart, lib/pages/forms_pages/components/question_option_widget.dart, lib/pages/forms_pages/components/questions_breeding_form.dart, lib/pages/forms_pages/components/small_question_option_widget.dart, lib/pages/main/components/custom_card_widget.dart, lib/pages/main/main_vc.dart, lib/pages/my_reports_pages/components/reports_list_widget.dart, lib/pages/my_reports_pages/my_reports_page.dart, lib/pages/notification_pages/notifications_page.dart, lib/pages/settings_pages/gallery_page.dart, lib/pages/settings_pages/partners_page.dart, lib/pages/settings_pages/settings_page.dart, lib/pages/settings_pages/tutorial_page.dart, lib/utils/PushNotificationsManager.dart, lib/utils/UserManager.dart, lib/utils/Utils.dart, lib/utils/clustering/report_geohash.dart
No ticket for this, but when digging through the codebase I found many commented out code. Maybe it makes sense to remove what is not used to have a cleaner workspace
=> Remove commented out code

assets/language/en.json, lib/pages/my_reports_pages/components/reports_list_widget.dart, lib/pages/my_reports_pages/my_reports_page.dart, lib/utils/Utils.dart
fixes #63 
| English | Spanish |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/98d6fe8c-d35f-46ea-a386-efa2ac953b05) | ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/e88ec79c-461f-49a7-a1ae-53305f2acee3) |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/ab760176-d343-432b-b533-97d5a80202f8) | - |
=> Change title for report type on "My data" -> List

lib/api/api.dart, lib/models/report.dart, lib/pages/forms_pages/biting_report_page.dart, lib/pages/forms_pages/breeding_report_page.dart, lib/pages/forms_pages/components/biting_location_form.dart, lib/pages/main/main_vc.dart, lib/pages/my_reports_pages/components/reports_list_widget.dart, lib/pages/my_reports_pages/my_reports_page.dart, lib/pages/settings_pages/settings_page.dart, lib/utils/UserManager.dart, lib/utils/Utils.dart, pubspec.lock, pubspec.yaml
fixes #77 
| 1 | 2 |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/ac300b99-88ad-4240-910d-f4f1eca26f59)  | ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/336889f7-6577-4fe4-a66f-22ffdce63aa8)  |
=> Add geocoding to display city in reports

android/app/src/main/AndroidManifest.xml
=> Bug fix duplicated icon

lib/pages/notification_pages/notifications_page.dart, lib/utils/PushNotificationsManager.dart
=> Open selected notification

lib/pages/info_pages/info_page.dart, pubspec.lock, pubspec.yaml
=> Upgrade webview

lib/utils/MyLocalizations.dart, pubspec.yaml
fixes #112 
Same change as #132 but targeted to main instead of v34
=> Fix app not opening when region is different

lib/utils/Utils.dart
=> use correct location permission string

lib/pages/main/main_vc.dart, lib/pages/settings_pages/gallery_page.dart, lib/pages/settings_pages/info_page.dart
=> Content of guide showing "Guide" instead of "Tutorial"

lib/pages/main/home_page.dart
=> Homepage - Add more margin between the text and the buttons

lib/pages/main/main_vc.dart
=> Display app version at the absolute bottom in the navigation drawer

lib/pages/my_reports_pages/components/reports_list_widget.dart, pubspec.lock, pubspec.yaml
fixes #90
GIF showing how it looks the first time I load the page vs the second time when it's already cached
=> Add cached images

lib/pages/settings_pages/consent_form.dart
=> Remove initial tutorial

android/build.gradle
=> Plugin require higher sdk version

lib/pages/main/drawer_and_header.dart
| First Header  | Second Header |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/bf34c4c4-478b-47dc-9c64-0bc03b0810fe) | ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/e02d64c0-0eeb-4384-a234-163febc20ba9) |
=> Add guide to send mosquitoes by email

lib/pages/main/drawer_and_header.dart, lib/pages/settings_pages/gallery_page.dart
=> After finishing the guide, go back to HomePage

lib/pages/forms_pages/adult_report_page.dart, lib/pages/forms_pages/components/add_photo_button_widget.dart, lib/pages/forms_pages/components/questions_breeding_form.dart
fixes #103 
| First Header  | Second Header |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/9f3bedf9-0582-40af-8487-890102c50816) | ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/7193f23b-9003-40fc-9b3e-a9566d58f529)  |
=> Ensure adult reports contain at least 1 photo

lib/api/api.dart, lib/pages/main/drawer_and_header.dart
fixes #156 
- I could reproduce the issue on v34. After the changes in this PR I can't reproduce it anymore so I think it's fixed, but since it didn't happen 100% of the cases, I am not 100% sure
=> Fix app freeze on first boot when trying to load from API

android/build.gradle
In my emulator it works with this new configuration, but we'll have to test it on more devices just in case
=> Update target sdk to 34

lib/pages/forms_pages/components/biting_form.dart, lib/pages/settings_pages/consent_form.dart, lib/pages/settings_pages/info_page.dart, lib/utils/Utils.dart
- Remove unused code
- Remove null check for variables that can't be null
=> Cleanup - Remove unused code and unnecessary null checkers

lib/pages/forms_pages/adult_report_page.dart, lib/pages/forms_pages/biting_report_page.dart, lib/pages/forms_pages/breeding_report_page.dart, lib/utils/UserManager.dart, lib/utils/Utils.dart, pubspec.lock, pubspec.yaml
fixes #148 
- According to https://pub.dev/packages/in_app_review#testing-read-carefully , the only way to test it is by building an appbundle and uploading it to Play Store as internal test
- I tested that once a review has been submitted, the app does not request again for a review after 6, 9, 12... reviews
| First Header  | Second Header | Result in PlayStore |
| ------------- | ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/e5c51c01-ebc0-4b89-ac06-1e121274577a) | ![image](https://github.com/user-attachments/assets/68e6474f-b8d0-4208-9fb7-ac1171e2cf5c) | ![image](https://github.com/user-attachments/assets/07319aa4-f48c-46fa-a21c-0b4d857550a7) |
=> Request users to submit a first review after they submit a 3rd, 4th, (6, 9, 12, 15...) report

lib/pages/settings_pages/components/hashtag.dart
fixes #190  ->  When pressing on 'space bar', the tag appears in a new box but it is not saved (the counter does not change and when you fold and unfold the menu again it does not appear)
=> Auto-tagging - Pressing space saves the tag

lib/pages/my_reports_pages/components/reports_list_widget.dart
=> Single Report view -> delete button inside a app bar

lib/api/api.dart, lib/utils/Utils.dart
Should we also add that to v34?
=> V35 - Remove /sessions

lib/pages/main/main_vc.dart
=> NavigationDestination - new style

lib/pages/main/drawer_and_header.dart
=> Fix menu order: Info and Settings

android/app/build.gradle, android/build.gradle, android/settings.gradle
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
=> Gradle - Migrate deprecated API to use declarative plugins block instead of apply script method

lib/pages/main/drawer_and_header.dart
=> Fix UUID overflow iOS

lib/main.dart, lib/pages/main/components/custom_card_widget.dart, lib/pages/main/drawer_and_header.dart, lib/pages/main/home_page.dart, lib/pages/notification_pages/notifications_page.dart
| Before  | After |
| ![image](https://github.com/user-attachments/assets/5e2af9a4-d2f3-4c85-a4a9-0ab74f521917) | ![image](https://github.com/user-attachments/assets/f0a1f838-dd6f-4f16-89ea-4ec803e71e5c) |
| Content Cell  | ![image](https://github.com/user-attachments/assets/c44b372d-5cc7-4dad-8154-af032c3a8619) |
| ![image](https://github.com/user-attachments/assets/7dfee1e7-235c-4390-80cb-5dea498e3947) | ![image](https://github.com/user-attachments/assets/667e6755-ef66-4962-a636-7e82204f87f7) |
=> #277: Set background color to white

lib/pages/main/home_page.dart
fixes #283 
| Before  | After |
| ![image](https://github.com/user-attachments/assets/f1887970-3542-401e-b2ea-95f52b273316) | ![image](https://github.com/user-attachments/assets/75ce9be3-ffc0-4040-a6cd-00d8aa341622) |
=> #283: Public map button: color and position

lib/pages/settings_pages/campaign_tutorial_page.dart, lib/pages/settings_pages/gallery_page.dart
=> 'PREV' button using same style + replace deprecated MaterialStateProperty

android/app/build.gradle, android/build.gradle, android/gradle.properties, android/settings.gradle
See: https://stackoverflow.com/questions/76108428/how-do-i-fix-namespace-not-specified-error-in-android-studio
=> Use Flutter's SDK version settings in build.gradle

android/app/src/main/AndroidManifest.xml, pubspec.yaml
Fixes #122
See: https://developer.android.com/design/ui/mobile/guides/home-screen/notifications
=> Set default icon for firebase notifications.

android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle
- Upgrade AGP dependency from 8.1.4 to 8.5.0
- Upgrade Gradle version to 8.7
=> Upgrade AGP to 8.5.0

lib/pages/my_reports_pages/components/reports_list_widget.dart
=> My Reports: Show report containers in white color

lib/pages/forms_pages/adult_report_page.dart, lib/pages/forms_pages/biting_report_page.dart, lib/pages/forms_pages/breeding_report_page.dart
https://stackoverflow.com/a/67990442
=> Type error: Null check operator used on a null value

lib/api/api.dart
=> Type error: type 'bool' is not a subtype of type 'int?'

lib/pages/forms_pages/components/biting_form.dart
=> Exception: StateError (Bad state: No element)

lib/pages/main/drawer_and_header.dart, lib/utils/Utils.dart
fixes #336 
The performance dropped significantly after this commit: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/324/files
When debugging, I see that the bottleneck is specifically at Utils.createNewReport because those changes are checking the location every time, which is an expensive operation and results in taking multiple seconds to start a report.
| Main branch  | This pull request |
| ![Image](https://github.com/user-attachments/assets/6275be0f-17cd-41dc-a761-317f1c25f461) | ![performance-issue-after](https://github.com/user-attachments/assets/06a82498-a238-4193-9e68-8f27cb012a4f)  |
=> Performance issue on HomePage when creating a new report of any type

.github/workflows/build_app.yml
=> Merge queue: Execute pull_request+merge_group and rename jobs

.github/workflows/build_app.yml, pubspec.yaml
Reproduce and prevent regression of #393 
Tested on android and iOS build:
=> Regression test to validate pubspec.lock on build stage (CI)

.github/workflows/integration_tests.yml
=> Fix non deterministic emulator on CI

lib/main.dart, lib/pages/main/drawer_and_header.dart, lib/providers/auth_provider.dart
=> Manage dio exceptions and show snackbar if login/createUser fails

lib/pages/forms_pages/biting_report_page.dart, lib/utils/PushNotificationsManager.dart
=> Refactor campaign code to reduce complexity
