Mosquito-Alert/Mosquito-Alert-Mobile-App

lib/utils/version_control.dart
Based on the information provided, Dribba GmbH does not hold copyright rights "All rights reserved". This pull requests removes the inexact language used to be closer to reality
=> Remove inconsistent "all rights reserved" language

lib/utils/MyLocalizations.dart
> https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/74#issuecomment-1921158145 Could you implement a fallback to the English version when no translation is available in the specified language? I prefer seeing an English word instead of an empty value.
=> Show string in English when there is no translation available in the local language

assets/config/dev.json, assets/config/prod.json, lib/api/api.dart, lib/app_config.dart, lib/main.dart, lib/main_dev.dart, lib/main_prod.dart, lib/pages/main/main_vc.dart, pubspec.yaml
fixes #41 
- To use different environment variables, dart requires the app to have different entry points (ie different files, main_prod.dart and main_dev.dart)
- This makes easier the future implementation of [Automate release of new versions to google play / apple store](#38) 
- To start in prod: Run the file main_prod.dart, or in cmd: `flutter run -t lib/main_prod.dart`
- By default the app is started in dev mode. It can also be started in dev mode by running any of the following:
- Run main.dart or main_dev.dart
- Run `flutter run` or `flutter run -t lib/main_dev.dart`
=> Generate environment specific configuration

lib/api/api.dart, lib/utils/Utils.dart
fixes #39 
- phone_upload_time only set on createReport of the api
- On createReport, set phone_upload_time to now() if version_number == 0, otherwise keep value (if not null)
=> phone_upload_time fields should be set on POST to API

lib/pages/settings_pages/settings_page.dart
Fix exception on output console when entering settings page
Set initially as `false` until the async method `initializeBgTracking()` finishes
=> Fix isBgTrackingEnabled not initialized

.gitignore, README.md, android/app/build.gradle, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/AppDelegate.swift, ios/Runner/Info.plist, lib/main.dart, lib/pages/settings_pages/settings_page.dart, lib/utils/BackgroundTracking.dart, lib/utils/UserManager.dart
fixes #9 
- Schedule a daily task at 00:00 that generated 5 random times for the day to collect the locations and send to the api
=> Optional background tracking taking 5 random times, instead of 5 regular times per day

lib/pages/forms_pages/adult_report_page.dart
relates to #103 
I'm still going to the "directly open camera, etc", but this would be a small change that forces adult report to contain photos:
=> Remove option "continue without photo"

lib/pages/forms_pages/components/whatsapp_camera.dart/camera_whatsapp.dart
I believe it could be due to not awaiting for future objects. After adding those missing `await`, I could not reproduce the issue anymore, so I think it's solved
```
W/velab.tigatrap( 5657): Long monitor contention with owner main (5657) at void android.hardware.camera2.impl.CameraDeviceImpl.close()(CameraDeviceImpl.java:1433) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 184ms
E/AndroidRuntime( 5657): FATAL EXCEPTION: CameraBackground
E/AndroidRuntime( 5657): Process: ceab.movelab.tigatrapp, PID: 5657
E/AndroidRuntime( 5657): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object …
```
=> Fix random crash when selecting a recent image from whatsapp camera (happened 10-20% of the time)

lib/pages/forms_pages/components/whatsapp_camera.dart/camera_whatsapp.dart
fixes #17 
> could the camera layout be adjusted to place the gallery button next to the shutter button (on its right) instead of in the top-right corner?
=> Move gallery button to bottom right

lib/pages/forms_pages/components/add_photo_button_widget.dart
| First Header  | Second Header |
| ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/d557509c-59ae-4db6-8d0a-04df4bbe9c74) | ![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/8a68ebad-ac2f-4192-b27e-be1cdc80677c) |
=> Fix null error when exiting camera without selecting a photo

lib/pages/forms_pages/adult_report_page.dart
Fix bug where it's possible to skip pages on adult pages after at least 1 photo has been attached
| Before | After |
| ![bug_skip_adult](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/dc4b669d-8183-4aad-a807-4b9a6a8122e2)  | ![fix_skip_adult](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/679c33e3-fcc9-4eba-a790-9ada07ec5e11) |
=> Fix bug where it's possible to skip pages on adult report after at least a photo has been attached

lib/pages/forms_pages/components/add_photo_button_widget.dart
fixes #17 
Also avoid opening the camera if there is already at least an image attached, which would be triggered if the users goes back during the report loop
| Adult | Breding site |
| ![directly_open_camera_adult](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/7fb23be0-c69e-44f3-89be-9257bb55e9fa) | ![directly_open_camera_site](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/4e82c9b3-2b23-4001-9dbe-78c623fa645c) |
=> Directly open camera instead of showing "Attach a photo" page

pubspec.yaml
On the camera whatsapp there is this warning that is gone when I update the minimum SDK to 2.15.0
=> Update min sdk to 2.15.0

lib/pages/settings_pages/components/hashtag.dart
fixes #190 -> The button with the 'X' is gray, but it should be white (always the same color as text).
=> Auto-tagging - Cancel color set to white

lib/pages/settings_pages/components/hashtag.dart
fixes #190 -> Users until now (schools) have been told that they should use '#' as a prefix, and now doing so appears two hashtags. Can this be avoided?
=> Auto-tagging - Avoid double hashtag

lib/pages/settings_pages/settings_page.dart
fixes #190
| If there's >= 1 tag, init unfolded | When deleting tag, it's still unfolded | When pressing enter, it's still unfolded |
| ------------- | ------------- | ------------- |
| ![init_unfolded](https://github.com/user-attachments/assets/94e04ba6-7304-44b5-b679-ea43e97bf7ef) | ![delete_does_not_close](https://github.com/user-attachments/assets/ab2e4e47-4ff3-4be1-8cf9-8771b113a271) | ![pressing_enter_keeps_unfolded](https://github.com/user-attachments/assets/1ab7890f-c763-4a4f-827f-649745085ce0) |
=> Auto-tagging - Keep extension tile open

lib/pages/settings_pages/components/hashtag.dart
fixes #195  -> It is expected that tags can be deleted using the 'delete' key on the keyboard
- Wrap the StringMultilineTag in a KeyboardListener to check when 'Backspace' is pressed
- Create 'currentWord' to only remove the last hashtag when it's an empty string (Otherwise it would remove the hashtag every time even if you are in the middle of creating a new hashtag, and press backspace)
=> Auto-tagging: handle backspace

android/app/build.gradle, android/build.gradle, lib/utils/Utils.dart, pubspec.lock, pubspec.yaml
- Upgrade kotlin, gradle and java to make easier the introduction of fastlane in #207
- Use `flutter pub outdated` to detect `upgradable` dependencies
=> Upgrade major versions of kotlin, gradle and other dependencies

android/build.gradle
Increase warning details in the log when running the app locally
Before:
After:
```
\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-15.2.0\android\src\main\java\io\flutter\n] getTo() in RemoteMessage has been deprecated
messageMap.put(KEY_TO, remoteMessage.getTo());
^
2 warnings
```
=> Enable -Xlint:deprecation

pubspec.yaml
Since having custom dependency versions is usually a bad practice, I think it's a good idea to add a comment explaining why we did that, so that in the future we don't revert it so easily, breaking something for iOS
=> workmanager: add explanation of why it's using a custom ref

android/app/src/main/kotlin/com/example/mosquito_alert_app/MainActivity.kt
This was the warning message being shown:
```
W/FlutterEngineCxnRegstry(10593): Attempted to register plugin (dev.fluttercommunity.workmanager.WorkmanagerPlugin@1244eeb) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@1436448).
```
Introduced here: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/commit/72b6c434c0eabb85da832ad7099ca47205cdd1b3
=> Removed duplicate workmanager registration message

pubspec.lock, pubspec.yaml
See: https://github.com/firebase/flutterfire/pull/16995
Solving this message
```
getTo() in RemoteMessage has been deprecated
if (remoteMessage.getTo() != null) {
^
/home/runner/.pub-cache/hosted/pub.dev/firebase_messaging-15.2.0/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java:51: warning: [deprecation] getTo() in RemoteMessage has been deprecated
messageMap.put(KEY_TO, remoteMessage.getTo());
```
=> Updated firebase_messaging to 15.2.4

lib/pages/forms_pages/components/add_other_report_form.dart, lib/pages/forms_pages/components/biting_form.dart, lib/pages/forms_pages/components/whatsapp_camera.dart/camera_whatsapp.dart, lib/pages/main/drawer_and_header.dart, lib/pages/settings_pages/campaign_tutorial_page.dart, lib/pages/settings_pages/components/settings_menu_widget.dart, lib/pages/settings_pages/gallery_page.dart, lib/pages/settings_pages/settings_page.dart, lib/utils/style.dart
`withOpacity` was deprecated on flutter 3.27.0 -> https://stackoverflow.com/questions/79284946/why-is-withopacity-deprecated-in-flutter-3-27-0-and-what-is-its-recommended-rep
`flutter analyze`
- Before:
`34 issues found. (ran in 63.3s)`
- After:
`16 issues found. (ran in 18.7s)`
=> Replace deprecated 'withOpacity'

lib/utils/Utils.dart
Fixes 4 `flutter analyze` issues
https://stackoverflow.com/questions/72039615/canlaunch-is-deprecated-in-flutter
=> Replace deprecated 'launch' and 'canLaunch'

lib/utils/Utils.dart
https://stackoverflow.com/questions/76312328/flutter-3-10-window-is-deprecated-and-shouldnt-be-used
Fixes 3 `flutter analyze` issues
```
info - 'window' is deprecated and shouldn't be used. Look up the current FlutterView from the context via View.of(context) or consult the PlatformDispatcher directly instead.    
Deprecated to prepare for the upcoming multi-window support. This feature was deprecated after v3.7.0-32.0.pre - lib\utils\Utils.dart:978:21 - deprecated_member_use
```
=> 'window' is deprecated and shouldn't be used

lib/pages/forms_pages/components/biting_form.dart, lib/pages/forms_pages/components/whatsapp_camera.dart/camera_whatsapp.dart
fixes #337 
Seems like the blue rectangle was used for debugging purposes and was set at blue with transparency, but this commit changed the behavior, most likely due to an extra dot by mistake (..withValues instead of .withValues) https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/327
| Main branch  | This pull request |
| ![Image](https://github.com/user-attachments/assets/1db17e00-9f5d-4bff-a2c7-2e2297c25121) | ![image](https://github.com/user-attachments/assets/6b567e83-4046-4a6e-89ed-99139a5d22ed) |
=> Fix bug of blue rectangle

android/app/src/main/AndroidManifest.xml, pubspec.yaml
Add required AD_ID to use Analytics on SDK 33+
Although the app does not use advertising features, Google Analytics (Firebase) may access the Advertising ID for analytics purposes
No changes were made to the app's logic or UI.
Reference:
- [Google Play Policy - Advertising ID](https://support.google.com/googleplay/android-developer/answer/6048248)
| Before | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/b817a95c-0f46-428e-a9f8-fb297d17b04d) | ![image](https://github.com/user-attachments/assets/97997336-1d2c-44c5-b46e-c5f5736d6939) |
=> Add Advertising ID permission for Google Analytics compliance with Play Store policy

.github/workflows/build_app.yml, pubspec.lock
1. Properly configure the merge queue
2. Fix CI bug when multiple PRs don't merge pubspec.lock correctly - fixes #393 
From the GitHub documentation:
> "To run status checks on merge queue entries, your workflow must be configured to run on the `merge_group` event."  
> — [GitHub Docs: Managing a merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
The merge queue forces the PRs to be merged one after another, where they must include the changes on main and the previous pull request, which should force the PRs to merge with correct pubspec.lock files
=> Add `merge_group` support to workflows to ensure correct CI and pubspec.lock consistency with merge queue
